[tox]
envlist = py3, typecheck, lint
isolated_build = true

[testenv]
deps = pytest
commands = pytest {posargs}

[testenv:typecheck]
deps =
    mypy
    pytest
commands = mypy {posargs: src tests}

[testenv:format]
skip_install = true
deps =
    black
commands = black {posargs: .}

[testenv:lint]
skip_install = true
deps =
    flake8
    flake8-bugbear
commands = flake8 {posargs: .}

[flake8]
max-line-length = 120
extend-ignore = E203
per-file-ignores =
    */__init__.py: F401
